name: release

on:
  push:
    branches:
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci

    steps:
      - uses: actions/checkout@v1
      - name: run postgres
        run: make postgresql
      - name: build image
        run: make py38
      - name: validate version
        run: make test-version
      - name: run flake8
        run: make test-flake8
      - name: run black
        run: make test-black
      - name: run tests
        run: make test-py38

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      PYTHON_ENV: ci
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v1
      - name: build python 3.8 image
        run: make py38
      - name: build python 3.8 bundle
        run: make bundle
      - name: release to pypi
        run: make release
